import React from 'react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { notFound } from 'next/navigation';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import '../../styles/globals.css';

import { routing } from '@/libs/i18n-navigation';

import Providers from './providers';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  if (process.env.NODE_ENV === 'development') {
    throw new Error('Đây là lỗi giả để kiểm tra global-error.tsx');
  }
  const { locale } = await params;
  const messages = await getMessages();

  if (!hasLocale(routing.locales, locale) || !messages) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${roboto.variable} antialiased`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
