name: Next Deployment

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          debug: true
          script: |
            cd /home/ubuntu/ethnic-village-travel-fe
            git fetch origin
            git checkout dev
            git pull
            docker build -t ethnic-village-travel-fe .
            docker stop ethnic-village-travel-fe || true
            docker rm ethnic-village-travel-fe || true
            docker run -d --name ethnic-village-travel-fe -p 3000:3000 ethnic-village-travel-fe
